@extends('layouts.desktop')
@section('title', 'Metas y comisiones')

@push('desktop-styles')
<style>
    .commission-v2{display:flex;flex-direction:column;gap:16px;max-width:1180px;margin:0 auto}.commission-hero{padding:22px;border-radius:18px;color:#fff;background:linear-gradient(135deg,#0f6cbd,#17478f);box-shadow:var(--shadow-4)}
    .commission-hero__top,.commission-row{display:flex;align-items:center;justify-content:space-between;gap:14px}.commission-hero h1{margin:0;font-size:1.42rem}.commission-hero p{margin:6px 0 0;opacity:.88}.commission-status{display:inline-flex;padding:7px 12px;border-radius:999px;font-size:.76rem;font-weight:800;text-transform:uppercase;background:rgba(255,255,255,.16)}
    .commission-toolbar,.commission-wizard{background:var(--surface);border:1px solid var(--stroke);border-radius:var(--r-lg);box-shadow:var(--shadow-2)}.commission-toolbar{padding:14px 16px;display:flex;align-items:end;gap:12px;flex-wrap:wrap}.commission-toolbar .desktop-field{margin:0;min-width:190px}.commission-toolbar__aside{margin-left:auto;display:flex;align-items:center;gap:8px}
    .commission-advanced{position:relative}.commission-advanced>summary{list-style:none;cursor:pointer}.commission-advanced>summary::-webkit-details-marker{display:none}.commission-advanced__panel{position:absolute;right:0;top:calc(100% + 8px);z-index:25;width:min(430px,90vw);padding:14px;border:1px solid var(--stroke);border-radius:14px;background:var(--surface);box-shadow:var(--shadow-8)}.commission-create{display:flex;gap:8px;align-items:end;padding-bottom:12px}.commission-create .desktop-field{margin:0;flex:1}.commission-manage__row{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:9px 4px;border-top:1px solid var(--divider)}
    .commission-wizard{overflow:hidden}.commission-stepper{display:grid;grid-template-columns:repeat(4,1fr);padding:18px 20px;border-bottom:1px solid var(--divider);background:var(--surface-sunken)}.commission-stepper__item{position:relative;display:flex;align-items:center;gap:9px;border:0;background:transparent;color:var(--text-2);text-align:left;padding:0 8px;cursor:pointer}.commission-stepper__item:not(:last-child)::after{content:"";position:absolute;left:calc(100% - 12px);right:-12px;top:17px;height:2px;background:var(--stroke)}.commission-stepper__number{position:relative;z-index:1;width:34px;height:34px;display:grid;place-items:center;flex:none;border-radius:50%;border:2px solid var(--stroke-strong);background:var(--surface);font-weight:800}.commission-stepper__text strong,.commission-stepper__text small{display:block}.commission-stepper__text strong{font-size:.83rem}.commission-stepper__text small{margin-top:2px;font-size:.68rem;color:var(--text-3)}.commission-stepper__item.is-active{color:var(--brand)}.commission-stepper__item.is-active .commission-stepper__number,.commission-stepper__item.is-done .commission-stepper__number{border-color:var(--brand);background:var(--brand);color:#fff}.commission-stepper__item.is-done:not(:last-child)::after{background:var(--brand)}
    .commission-step-panel[hidden]{display:none!important}.commission-step-panel{animation:commission-step-in .18s ease}.commission-step-panel__head{display:flex;gap:14px;align-items:flex-start;padding:24px 26px 17px;border-bottom:1px solid var(--divider)}.commission-step-panel__icon{width:42px;height:42px;display:grid;place-items:center;flex:none;border-radius:12px;background:var(--brand-soft);color:var(--brand);font-size:1.12rem}.commission-step-panel__head h2{margin:0;font-size:1.18rem}.commission-step-panel__head p{margin:5px 0 0;color:var(--text-2);font-size:.84rem;line-height:1.5}.commission-step-panel__body{padding:22px 26px}.commission-step-panel__footer{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:16px 26px;border-top:1px solid var(--divider);background:var(--surface-sunken)}
    .commission-choice-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.commission-choice{display:flex;align-items:center;gap:12px;padding:15px;border:1px solid var(--stroke);border-radius:12px;background:var(--surface);cursor:pointer;transition:.15s}.commission-choice:hover{border-color:var(--brand)}.commission-choice input{width:18px;height:18px}.commission-choice:has(input:checked){border-color:var(--brand);background:var(--brand-soft)}.commission-choice strong,.commission-choice small{display:block}.commission-choice small{margin-top:3px;color:var(--text-2);font-size:.74rem}
    .commission-departments{display:flex;flex-direction:column;gap:13px}.commission-department{border:1px solid var(--stroke);border-radius:14px;overflow:hidden}.commission-department__top{display:flex;gap:12px;align-items:center;padding:15px;background:var(--surface-sunken)}.commission-department__top strong{flex:1}.commission-department__body{padding:16px;display:grid;gap:15px}.commission-department.is-disabled{opacity:.56}.commission-fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.commission-lines-details{border:1px solid var(--stroke);border-radius:11px;padding:11px 13px}.commission-lines-details summary{cursor:pointer;color:var(--brand);font-size:.8rem;font-weight:700}.commission-lines{display:flex;flex-wrap:wrap;gap:7px;margin-top:12px}.commission-line{position:relative}.commission-line input{position:absolute;opacity:0;pointer-events:none}.commission-line span{display:block;padding:7px 10px;border:1px solid var(--stroke);border-radius:999px;color:var(--text-2);font-size:.76rem;cursor:pointer}.commission-line input:checked+span{border-color:var(--brand);background:var(--brand-soft);color:var(--brand);font-weight:700}
    .commission-reference{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.commission-reference div,.commission-summary-card{padding:12px;border-radius:11px;background:var(--surface-sunken)}.commission-reference span,.commission-summary-card span{display:block;color:var(--text-2);font-size:.68rem;text-transform:uppercase}.commission-reference strong,.commission-summary-card strong{display:block;margin-top:4px;font-size:.9rem}.commission-help{padding:12px 14px;border-radius:10px;background:#eef6ff;color:#154f86;font-size:.79rem;line-height:1.5}.commission-note{color:var(--text-2);font-size:.77rem}.commission-danger-note{padding:12px;border-radius:10px;background:#fff4e5;color:#7a4a00;font-size:.8rem;line-height:1.5}
    .commission-seller-tools{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:12px}.commission-seller-search{width:min(300px,100%);min-height:39px;padding:8px 10px;border:1px solid var(--stroke);border-radius:9px;background:var(--surface);color:var(--text)}.commission-sellers{overflow:auto;border:1px solid var(--stroke);border-radius:12px}.commission-table{width:100%;border-collapse:collapse;min-width:940px}.commission-table th{padding:10px;text-align:left;font-size:.7rem;text-transform:uppercase;color:var(--text-2);background:var(--surface-sunken);border-bottom:1px solid var(--stroke)}.commission-table td{padding:10px;border-bottom:1px solid var(--divider);vertical-align:middle;font-size:.82rem}.commission-table tr:last-child td{border-bottom:0}.commission-table input,.commission-table select{width:100%;min-height:36px;padding:7px 8px;border:1px solid var(--stroke);border-radius:8px;background:var(--surface);color:var(--text)}.commission-table .seller-toggle{width:auto}.commission-estimate__percent{min-width:130px}.commission-progress{height:7px;overflow:hidden;border-radius:999px;background:var(--surface-sunken);margin-top:4px}.commission-progress span{display:block;height:100%;border-radius:inherit;background:linear-gradient(90deg,#0f6cbd,#16a36a)}.commission-empty{padding:24px;text-align:center;color:var(--text-2)}
    .commission-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-bottom:18px}.commission-review-section+.commission-review-section{margin-top:20px}.commission-review-section h3{margin:0 0 10px;font-size:.92rem}.commission-final-actions{display:flex;align-items:center;justify-content:flex-end;gap:8px;flex-wrap:wrap}.commission-error{display:none;margin:0 26px 18px;padding:10px 12px;border-radius:9px;background:#fff0f0;color:#a32b2b;font-size:.8rem}.commission-error.is-visible{display:block}
    @keyframes commission-step-in{from{opacity:.6;transform:translateX(8px)}to{opacity:1;transform:none}}
    @media(max-width:900px){.commission-stepper__text small{display:none}.commission-stepper__item{justify-content:center}.commission-summary{grid-template-columns:repeat(2,1fr)}.commission-reference{grid-template-columns:1fr}.commission-fields{grid-template-columns:1fr}}
    @media(max-width:620px){.commission-choice-grid{grid-template-columns:1fr}.commission-stepper{padding:14px 5px}.commission-stepper__item{padding:0 2px;flex-direction:column;text-align:center;gap:5px}.commission-stepper__text strong{font-size:.68rem}.commission-stepper__item:not(:last-child)::after{top:17px;left:calc(50% + 18px);right:calc(-50% + 18px)}.commission-step-panel__head,.commission-step-panel__body{padding-left:16px;padding-right:16px}.commission-step-panel__footer{padding:14px 16px}.commission-summary{grid-template-columns:1fr 1fr}.commission-toolbar__aside{margin-left:0;width:100%;justify-content:flex-start}.commission-create{flex-wrap:wrap}}
</style>
@endpush

@section('desktop-toolbar')
<div class="page-head"><span class="page-head__title">Metas y comisiones</span><span class="page-head__sub">Asistente mensual paso a paso</span></div>
@endsection

@section('content')
@php
    $estado=$periodo?->cmp_estatus??'sin configurar';
    $bloqueado=$estado==='cerrado';
    $primerError=collect($errors->keys())->first();
    $pasoError=str_starts_with((string)$primerError,'almacen')?1:(str_starts_with((string)$primerError,'departamentos')?2:(str_starts_with((string)$primerError,'vendedores')?3:($errors->any()?4:null)));
    $pasoInicial=$pasoError??($periodo?4:1);
@endphp
<div class="commission-v2" data-commission-wizard data-initial-step="{{ $pasoInicial }}">
    <section class="commission-hero"><div class="commission-hero__top"><div><h1>Configura un periodo sin complicaciones</h1><p>Completa un paso a la vez. Nada se publica al vendedor hasta que apruebes las metas.</p></div><span class="commission-status">{{ str($estado)->headline() }}</span></div></section>
    @if($errors->any())<div class="alert alert-danger"><strong>No se guardaron los cambios.</strong> Ve al paso marcado y revisa los campos indicados.</div>@endif
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif

    <section class="commission-toolbar">
        <form method="GET" class="commission-row"><div class="desktop-field"><label for="commission-period">Mes que vas a configurar</label><input id="commission-period" type="month" name="periodo" value="{{ $periodoTexto }}"></div><button class="desktop-btn desktop-btn--primary" type="submit">Abrir mes</button></form>
        <div class="commission-toolbar__aside">
            <a class="desktop-btn desktop-btn--ghost" href="{{ route('desktop.operacion.gestion_configuraciones.comisiones.historico.index') }}">Capturar ventas históricas</a>
            @if($legacyCount>0)<a class="desktop-btn desktop-btn--ghost" href="{{ route('reportes.show',['reporte'=>'ventas-comisiones']) }}">Histórico anterior</a>@endif
            <details class="commission-advanced"><summary class="desktop-btn desktop-btn--ghost">Opciones avanzadas</summary><div class="commission-advanced__panel">
                <form method="POST" action="{{ route('desktop.operacion.gestion_configuraciones.comisiones.departamentos.store') }}" class="commission-create">@csrf<div class="desktop-field"><label for="new-department">Crear departamento</label><input id="new-department" name="nombre" maxlength="120" placeholder="Ej. Hogar" required></div><button class="desktop-btn desktop-btn--ghost" type="submit">Crear</button></form>
                @foreach($departamentosCatalogo as $item)<div class="commission-manage__row"><span><strong>{{ $item->cmd_nombre }}</strong><br><small>{{ str($item->cmd_estatus)->headline() }}</small></span><form method="POST" action="{{ route('desktop.operacion.gestion_configuraciones.comisiones.departamentos.estatus',$item) }}">@csrf @method('PATCH')<input type="hidden" name="estatus" value="{{ $item->cmd_estatus==='activo'?'inactivo':'activo' }}"><button class="desktop-btn desktop-btn--ghost" type="submit">{{ $item->cmd_estatus==='activo'?'Retirar':'Activar' }}</button></form></div>@endforeach
            </div></details>
        </div>
    </section>

    @if($periodo&&$estado==='borrador')<form id="commission-approve" method="POST" action="{{ route('reportes.comisiones.calcular') }}">@csrf<input type="hidden" name="periodo" value="{{ $periodoTexto }}"></form>@endif
    @if($periodo&&$estado==='aprobado')<form id="commission-close" method="POST" action="{{ route('reportes.comisiones.cerrar') }}" onsubmit="return confirm('¿Cerrar el periodo? Los resultados quedarán congelados y ya no podrán modificarse.');">@csrf<input type="hidden" name="periodo" value="{{ $periodoTexto }}"></form>@endif

    <form id="commission-config" class="commission-wizard" method="POST" action="{{ route('desktop.operacion.gestion_configuraciones.comisiones.update') }}" data-ls-autocomplete="admin">
        @csrf @method('PUT')<input type="hidden" name="periodo" value="{{ $periodoTexto }}">
        <nav class="commission-stepper" aria-label="Pasos de configuración">
            @foreach([[1,'Periodo','Almacenes'],[2,'Departamentos','Líneas y meta'],[3,'Equipo','Vendedores'],[4,'Revisión','Publicar o cerrar']] as [$numero,$titulo,$subtitulo])
                <button class="commission-stepper__item" type="button" data-step-target="{{ $numero }}"><span class="commission-stepper__number">{{ $numero }}</span><span class="commission-stepper__text"><strong>{{ $titulo }}</strong><small>{{ $subtitulo }}</small></span></button>
            @endforeach
        </nav>

        <section class="commission-step-panel" data-step-panel="1">
            <header class="commission-step-panel__head"><span class="commission-step-panel__icon"><i class="ti tabler-building-store"></i></span><div><h2>¿Qué almacenes participan?</h2><p>Se sumarán únicamente las ventas registradas en los almacenes que selecciones.</p></div></header>
            <div class="commission-step-panel__body"><div class="commission-choice-grid">@forelse($almacenes as $almacen)<label class="commission-choice"><input type="checkbox" name="almacen_ids[]" value="{{ $almacen->alm_id }}" @checked(in_array((string)$almacen->alm_id,array_map('strval',old('almacen_ids',$almacenesSeleccionados)),true)) @disabled($bloqueado)><span><strong>{{ $almacen->alm_nombre }}</strong><small>Incluir ventas de este almacén</small></span></label>@empty<div class="commission-empty">No hay almacenes activos.</div>@endforelse</div></div>
            <p class="commission-error" data-step-error="1"></p>
            <footer class="commission-step-panel__footer"><span class="commission-note">Paso 1 de 4</span><button class="desktop-btn desktop-btn--primary" type="button" data-next-step="2">Continuar</button></footer>
        </section>

        <section class="commission-step-panel" data-step-panel="2" hidden>
            <header class="commission-step-panel__head"><span class="commission-step-panel__icon"><i class="ti tabler-category-2"></i></span><div><h2>Define departamentos y metas</h2><p>Activa solo los departamentos que participarán. La meta común se aplicará inicialmente a sus vendedores.</p></div></header>
            <div class="commission-step-panel__body commission-departments">
                @foreach($departamentos as $departamento)
                    @php
                        $config=$configDepartamentos->get($departamento->cmd_id);
                        $habilitado=(bool)old("departamentos.{$departamento->cmd_id}.habilitado",$periodo?(bool)$config:$departamento->lineas->isNotEmpty());
                        $seleccionadas=$periodo?collect($lineasPeriodo->get($departamento->cmd_id,[]))->pluck('cml_lna_id')->all():$departamento->lineas->pluck('lna_id')->all();
                    @endphp
                    <article class="commission-department" data-department>
                        <div class="commission-department__top"><input type="hidden" name="departamentos[{{ $departamento->cmd_id }}][habilitado]" value="0"><input class="department-toggle" type="checkbox" name="departamentos[{{ $departamento->cmd_id }}][habilitado]" value="1" @checked($habilitado) @disabled($bloqueado)><strong>{{ $departamento->cmd_nombre }}</strong><span class="commission-note">{{ $config?->cpd_origen_meta==='historica'?'Con referencia histórica':'Meta manual inicial' }}</span></div>
                        <div class="commission-department__body">
                            <div class="commission-fields"><div class="desktop-field"><label>Meta común por vendedor ($)</label><input type="number" min="0" step="0.01" name="departamentos[{{ $departamento->cmd_id }}][meta_comun]" value="{{ old("departamentos.{$departamento->cmd_id}.meta_comun",$config?->cpd_meta_comun) }}" placeholder="Ej. 250000" @disabled($bloqueado)><small class="commission-note">En el primer año Administración captura esta cantidad.</small></div><div class="desktop-field"><label>Incremento sobre el histórico (%)</label><input type="number" min="0" max="100" step="0.01" name="departamentos[{{ $departamento->cmd_id }}][incremento_meta]" value="{{ old("departamentos.{$departamento->cmd_id}.incremento_meta",$config?->cpd_incremento_meta??0) }}" @disabled($bloqueado)><small class="commission-note">Se usará cuando ya exista el mismo mes del año anterior.</small></div></div>
                            <details class="commission-lines-details"><summary><span data-line-count>Seleccionar líneas</span></summary><div class="commission-lines">@foreach($lineas as $linea)<label class="commission-line"><input type="checkbox" name="departamentos[{{ $departamento->cmd_id }}][linea_ids][]" value="{{ $linea->lna_id }}" @checked(in_array((string)$linea->lna_id,array_map('strval',old("departamentos.{$departamento->cmd_id}.linea_ids",$seleccionadas)),true)) @disabled($bloqueado)><span>{{ $linea->lna_nombre }}</span></label>@endforeach</div></details>
                            @if($config)<div class="commission-reference"><div><span>Venta anterior</span><strong>${{ number_format((float)$config->cpd_ventas_historicas,2) }}</strong></div><div><span>Autoservicio excluido</span><strong>− ${{ number_format((float)$config->cpd_autoservicio_historico,2) }}</strong></div><div><span>Meta sugerida</span><strong>{{ $config->cpd_meta_sugerida!==null?'$'.number_format((float)$config->cpd_meta_sugerida,2):'Sin histórico' }}</strong></div></div>@endif
                        </div>
                    </article>
                @endforeach
                <div class="commission-help"><strong>¿Cómo se obtiene la meta futura?</strong><br>(Ventas del mismo mes anterior − autoservicio) ÷ vendedores del periodo, más el incremento definido.</div>
            </div>
            <p class="commission-error" data-step-error="2"></p>
            <footer class="commission-step-panel__footer"><button class="desktop-btn desktop-btn--ghost" type="button" data-previous-step="1">Regresar</button><button class="desktop-btn desktop-btn--primary" type="button" data-next-step="3">Continuar</button></footer>
        </section>

        <section class="commission-step-panel" data-step-panel="3" hidden>
            <header class="commission-step-panel__head"><span class="commission-step-panel__icon"><i class="ti tabler-users"></i></span><div><h2>Selecciona el equipo del mes</h2><p>Busca al vendedor, activa su participación y asigna departamento. La tasa normal es 0.9%.</p></div></header>
            <div class="commission-step-panel__body">
                <div class="commission-seller-tools"><span class="commission-note"><strong data-seller-count>0</strong> vendedores seleccionados</span><input id="commission-seller-search" class="commission-seller-search" type="search" placeholder="Buscar por nombre o usuario" aria-label="Buscar vendedor"></div>
                <div class="commission-sellers"><table class="commission-table"><thead><tr><th>Participa</th><th>Vendedor</th><th>Número</th><th>Departamento</th><th>Meta individual</th><th>Tasa</th><th>Motivo de ajuste</th></tr></thead><tbody>
                    @foreach($usuarios as $usuario)@php $p=$participantes->get($usuario->usr_id);$activo=(bool)old("vendedores.{$usuario->usr_id}.habilitado",(bool)$p); @endphp
                    <tr data-seller-row><td><input class="seller-toggle" type="checkbox" name="vendedores[{{ $usuario->usr_id }}][habilitado]" value="1" @checked($activo) @disabled($bloqueado)></td><td><strong>{{ $usuario->usr_nombre }}</strong><br><span class="commission-note">{{ $usuario->usr_usuario }}</span></td><td><input name="vendedores[{{ $usuario->usr_id }}][numero]" value="{{ old("vendedores.{$usuario->usr_id}.numero",$p?->cpt_numero_vendedor) }}" maxlength="40" placeholder="Ej. 5" @disabled($bloqueado)></td><td><select name="vendedores[{{ $usuario->usr_id }}][departamento_id]" @disabled($bloqueado)><option value="">Selecciona</option>@foreach($departamentos as $departamento)<option value="{{ $departamento->cmd_id }}" @selected((string)old("vendedores.{$usuario->usr_id}.departamento_id",$p?->departamentoPeriodo?->cpd_cmd_id)===(string)$departamento->cmd_id)>{{ $departamento->cmd_nombre }}</option>@endforeach</select></td><td><input type="number" min="0" step="0.01" name="vendedores[{{ $usuario->usr_id }}][meta]" value="{{ old("vendedores.{$usuario->usr_id}.meta",$p?->cpt_meta_individual) }}" placeholder="Usar meta común" @disabled($bloqueado)></td><td><select name="vendedores[{{ $usuario->usr_id }}][tasa]" @disabled($bloqueado)>@foreach([0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1] as $tasa)<option value="{{ $tasa }}" @selected((float)old("vendedores.{$usuario->usr_id}.tasa",$p?->cpt_tasa_comision??0.9)===(float)$tasa)>{{ number_format($tasa,1) }}%</option>@endforeach</select></td><td><input name="vendedores[{{ $usuario->usr_id }}][motivo]" value="{{ old("vendedores.{$usuario->usr_id}.motivo",$p?->cpt_motivo_ajuste) }}" maxlength="500" placeholder="Solo si cambia meta o tasa" @disabled($bloqueado)></td></tr>
                    @endforeach
                </tbody></table></div>
            </div>
            <p class="commission-error" data-step-error="3"></p>
            <footer class="commission-step-panel__footer"><button class="desktop-btn desktop-btn--ghost" type="button" data-previous-step="2">Regresar</button><button class="desktop-btn desktop-btn--primary" type="button" data-next-step="4">Revisar configuración</button></footer>
        </section>

        <section class="commission-step-panel" data-step-panel="4" hidden>
            <header class="commission-step-panel__head"><span class="commission-step-panel__icon"><i class="ti tabler-clipboard-check"></i></span><div><h2>Revisa antes de publicar</h2><p>Confirma la configuración y consulta el avance. El vendedor nunca verá los importes de esta pantalla.</p></div></header>
            <div class="commission-step-panel__body">
                <div class="commission-summary"><div class="commission-summary-card"><span>Periodo</span><strong>{{ $periodoTexto }}</strong></div><div class="commission-summary-card"><span>Almacenes</span><strong data-summary-warehouses>0</strong></div><div class="commission-summary-card"><span>Departamentos</span><strong data-summary-departments>0</strong></div><div class="commission-summary-card"><span>Vendedores</span><strong data-summary-sellers>0</strong></div></div>
                <div class="commission-review-section"><h3>{{ $bloqueado?'Resultado definitivo':'Avance y comisión estimada' }}</h3>
                    @if($estimaciones->isEmpty())<div class="commission-empty">Primero guarda la configuración. Después podrás aprobarla y publicar el avance.</div>@else<div class="commission-sellers"><table class="commission-table"><thead><tr><th>Vendedor</th><th>Departamento</th><th>Ventas netas</th><th>Meta</th><th>Avance</th><th>Tasa</th><th>{{ $bloqueado?'Comisión final':'Comisión estimada' }}</th></tr></thead><tbody>@foreach($estimaciones as $estimacion)<tr><td><strong>{{ $estimacion->numero }}</strong> · {{ $estimacion->nombre }}</td><td>{{ $estimacion->departamento }}</td><td>${{ number_format($estimacion->ventas,2) }}</td><td>${{ number_format($estimacion->meta,2) }}</td><td class="commission-estimate__percent"><strong>{{ number_format($estimacion->cumplimiento,2) }}%</strong><div class="commission-progress"><span style="width:{{ min(100,max(0,$estimacion->cumplimiento)) }}%"></span></div></td><td>{{ number_format($estimacion->tasa,1) }}%</td><td><strong>${{ number_format($estimacion->comision,2) }}</strong></td></tr>@endforeach</tbody></table></div>@endif
                </div>
                @if($estado==='aprobado')<div class="commission-danger-note mt-3"><strong>Este periodo ya está publicado.</strong> Si guardas una corrección, explica el motivo. El sistema conservará el antes y el después en la bitácora.</div><div class="desktop-field mt-3"><label for="change-reason">Motivo de la corrección</label><textarea id="change-reason" name="motivo_cambio" rows="2" maxlength="1000" placeholder="Ej. Se corrigió la asignación del vendedor...">{{ old('motivo_cambio') }}</textarea></div>@endif
                @if($bloqueado)<div class="commission-danger-note mt-3"><strong>Periodo cerrado.</strong> Los resultados están congelados y disponibles únicamente para consulta.</div>@endif
            </div>
            <p class="commission-error" data-step-error="4"></p>
            <footer class="commission-step-panel__footer"><button class="desktop-btn desktop-btn--ghost" type="button" data-previous-step="3">Regresar</button><div class="commission-final-actions">
                @unless($bloqueado)<button type="submit" class="desktop-btn desktop-btn--ghost">{{ $periodo?'Guardar cambios':'Guardar borrador' }}</button>@endunless
                @if($periodo&&$estado==='borrador'&&$puedeAprobar)<button type="submit" form="commission-approve" class="desktop-btn desktop-btn--primary">Aprobar y publicar avance</button>@endif
                @if($periodo&&$estado==='aprobado'&&$puedeCerrar)<button type="submit" form="commission-close" class="desktop-btn desktop-btn--danger">Cerrar periodo</button>@endif
            </div></footer>
        </section>
    </form>
</div>
@endsection

@push('desktop-scripts')
<script>
document.addEventListener('DOMContentLoaded',function(){
    const wizard=document.querySelector('[data-commission-wizard]');if(!wizard)return;
    const locked={{ $bloqueado?'true':'false' }};let current=Number(wizard.dataset.initialStep||1);
    const form=document.getElementById('commission-config');const panels=Array.from(wizard.querySelectorAll('[data-step-panel]'));const targets=Array.from(wizard.querySelectorAll('[data-step-target]'));
    const rows=Array.from(wizard.querySelectorAll('[data-seller-row]'));const departments=Array.from(wizard.querySelectorAll('[data-department]'));
    function showStep(step){current=Math.max(1,Math.min(4,Number(step)));panels.forEach(p=>p.hidden=Number(p.dataset.stepPanel)!==current);targets.forEach(b=>{const n=Number(b.dataset.stepTarget);b.classList.toggle('is-active',n===current);b.classList.toggle('is-done',n<current);b.setAttribute('aria-current',n===current?'step':'false');});refreshSummary();form?.scrollIntoView({behavior:'smooth',block:'start'});}
    function showError(step,message){const el=wizard.querySelector('[data-step-error="'+step+'"]');if(el){el.textContent=message;el.classList.add('is-visible');}}
    function clearError(step){wizard.querySelector('[data-step-error="'+step+'"]')?.classList.remove('is-visible');}
    function validate(step){clearError(step);if(locked)return true;if(step===1&&!wizard.querySelector('input[name="almacen_ids[]"]:checked')){showError(step,'Selecciona al menos un almacén para continuar.');return false;}if(step===2){const active=departments.filter(d=>d.querySelector('.department-toggle')?.checked);if(!active.length){showError(step,'Activa al menos un departamento.');return false;}if(active.some(d=>!d.querySelector('input[name*="[linea_ids]"]:checked'))){showError(step,'Cada departamento activo debe tener al menos una línea.');return false;}}if(step===3&&!rows.some(r=>r.querySelector('.seller-toggle')?.checked)){showError(step,'Selecciona al menos un vendedor para continuar.');return false;}return true;}
    function refreshDepartment(card){const toggle=card.querySelector('.department-toggle');const enabled=!locked&&Boolean(toggle?.checked);card.classList.toggle('is-disabled',!toggle?.checked);card.querySelectorAll('.commission-department__body input').forEach(field=>field.disabled=!enabled);const count=card.querySelectorAll('input[name*="[linea_ids]"]:checked').length;const label=card.querySelector('[data-line-count]');if(label)label.textContent=count+' línea'+(count===1?' seleccionada':'s seleccionadas');}
    function refreshSeller(row){const toggle=row.querySelector('.seller-toggle');const enabled=!locked&&Boolean(toggle?.checked);row.style.opacity=toggle?.checked?'1':'.48';row.querySelectorAll('input:not(.seller-toggle),select').forEach(field=>field.disabled=!enabled);refreshSummary();}
    function refreshSummary(){const warehouses=wizard.querySelectorAll('input[name="almacen_ids[]"]:checked').length;const activeDepartments=departments.filter(d=>d.querySelector('.department-toggle')?.checked).length;const activeSellers=rows.filter(r=>r.querySelector('.seller-toggle')?.checked).length;wizard.querySelectorAll('[data-summary-warehouses]').forEach(e=>e.textContent=warehouses);wizard.querySelectorAll('[data-summary-departments]').forEach(e=>e.textContent=activeDepartments);wizard.querySelectorAll('[data-summary-sellers],[data-seller-count]').forEach(e=>e.textContent=activeSellers);}
    targets.forEach(button=>button.addEventListener('click',()=>showStep(button.dataset.stepTarget)));wizard.querySelectorAll('[data-next-step]').forEach(button=>button.addEventListener('click',()=>{if(validate(current))showStep(button.dataset.nextStep);}));wizard.querySelectorAll('[data-previous-step]').forEach(button=>button.addEventListener('click',()=>showStep(button.dataset.previousStep)));
    departments.forEach(card=>{card.querySelector('.department-toggle')?.addEventListener('change',()=>refreshDepartment(card));card.querySelectorAll('input[name*="[linea_ids]"]').forEach(input=>input.addEventListener('change',()=>refreshDepartment(card)));refreshDepartment(card);});
    rows.forEach(row=>{row.querySelector('.seller-toggle')?.addEventListener('change',()=>refreshSeller(row));refreshSeller(row);});
    document.getElementById('commission-seller-search')?.addEventListener('input',function(){const term=this.value.trim().toLocaleLowerCase('es');rows.forEach(row=>row.hidden=term!==''&&!row.innerText.toLocaleLowerCase('es').includes(term));});
    showStep(current);
});
</script>
@endpush
