<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>Laisuriana.PrintAgent.Setup</AssemblyName>
    <RootNamespace>Laisuriana.PrintAgent.Setup</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Payload\**\*">
      <LogicalName>Payload.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
